# Generated by Django 4.2.30 on 2026-04-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('precio', models.FloatField(max_length=32, verbose_name='Precio')),
                ('existencias', models.IntegerField(verbose_name='Existencias')),
            ],
        ),
    ]
